server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: GATEWAY-SERVICE
  main:
    web-application-type: reactive
  codec:
    max-in-memory-size: 100MB
  webflux:
    multipart:
      max-in-memory-size: 100MB
      max-disk-usage-per-part: 100MB
      max-parts: 1
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: false # bạn dùng RouteLocator, nên phải để false
          lower-case-service-id: true
  data:
    redis:
      host: localhost
      port: 6380

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

jwt:
  secret: 4f9c1f5e70ee039c9f6fab00b56531e8c0e97b207f96c2bcc7177a7cba528a138a02985e1c10f73c7220e133351a19f8e6f242fd155ebc08c5c9ac7693d5007d

gateway:
  x-api-key: api-key

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org.springframework.web: DEBUG
    org.springframework.security: TRACE
    web: TRACE

# Nếu app này không dùng database, thì disable datasource autoconfig
spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
