server:
  port: 8084

spring:
  application:
    name: NOTI-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/noti_db
    username: eMartix
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: c4f4a58defb84f
    password: fa43c9c4f132ce
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    test-connection: true

  rabbitmq:
    host: localhost
    port: 5672
    username: eMartix
    password: 12345

# Actuators endpoints for Circuit Breaker
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# Circuit Breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      NOTI-SERVICE:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      NOTI-SERVICE:
        maxAttempts: 5
        waitDuration: 2s
